<?php
/***************************************************************************
 *						Theme Settings
 * 	----------------------------------------------------------------------
 * 						DO NOT EDIT THIS FILE
 *	----------------------------------------------------------------------
 *
 *  					Copyright (C) Themify
 * 						http://themify.me
 *
 ***************************************************************************/

$themify_theme_config = array();
$themify_theme_config['folders'] = array(
	'images' => array(
		'src' => 'uploads/'
	)
);

/* 	Settings Panel
/***************************************************************************/	
$themify_theme_config['panel']['settings']['tab']['general'] = array(
	'title' => __('General', 'themify'),		
	'id' => 'general',
	'custom-module' => array(
		array(
			'title' => __('Favicon', 'themify'),
			'function' => 'favicon',
			'target' => 'uploads/favicon/'
		),
		array(
			'title' => __('Custom Feed URL', 'themify'),
			'function' => 'custom_feed_url'
		),
		array(
			'title' => __('Header Code', 'themify'),
			'function' => 'header_html'
		),
		array(
			'title' => __('Footer Code', 'themify'),
			'function' => 'footer_html'
		),
		array(
			'title' => __('Search Settings', 'themify'),
			'function' => 'search_settings'
		),
		array(
			'title' => __('Error 404 Page', 'themify'),
			'function' => 'page_404_settings'
		),
		array(
			'title' => __('Feed Settings', 'themify'),
			'function' => 'feed_settings'
		),
		
	)
);

$themify_theme_config['panel']['settings']['tab']['default_layouts'] = array(
	'title' => __('Default Layouts', 'themify'),
	'id' => 'default_layouts',
	'custom-module' => array(
		array(
			'title' => __('Default Archive Post Layout', 'themify'),
			'function' => 'default_layout'
		),
		array(
			'title' => __('Default Single Post Layout', 'themify'),
			'function' => 'default_post_layout'
		),
		array(
			'title' => __('Default Page Layout', 'themify'),
			'function' => 'default_page_layout'
		)
	)
);

$themify_theme_config['panel']['settings']['tab']['portfolio_layouts'] = array(
	'title' => __('Portfolio Layouts', 'themify'),
	'id' => 'portfolio_layouts',
	'custom-module' => array(
		array(
			'title' => __('Default Archive Portfolio Layout', 'themify'),
			'function' => 'default_portfolio_index_layout'
		),
		array(
			'title' => __('Default Single Portfolio Layout', 'themify'),
			'function' => 'default_portfolio_single_layout'
		),
		array(
			'title' => __('Portfolio Permalink', 'themify'),
			'function' => 'portfolio_slug'
		)
	)
);


$themify_theme_config['panel']['settings']['tab']['theme_settings'] = array(
	'title' => __('Theme Settings', 'themify'),
	'id' => 'theme_settings',
	'custom-module' => array(
		array(
			'title' => __('Responsive Design', 'themify'),
			'function' => 'disable_responsive_design_option'
		),
		array(
			'title' => __('WordPress Gallery Lightbox', 'themify'),
			'function' => 'gallery_plugins'
		),
		array(
			'title' => __('Header Design', 'themify'),
			'function' => 'header_design'
		),
		array(
			'title' => __('Social Share', 'themify'),
			'function' => 'social_share_module'
		),
		array(
			'title' => __('Exclude RSS Link', 'themify'),
			'function' => 'exclude_rss'
		),
		array(
			'title' => __('Exclude Search Form', 'themify'),
			'function' => 'exclude_search_form'
		),
		array(
			'title' => __('Pagination Option', 'themify'),
			'function' => 'pagination_infinite'
		),
		array(
			'title' => __('Footer Text 1', 'themify'),
			'function' => 'footer_text_left'
		),
		array(
			'title' => __('Footer Text 2', 'themify'),
			'function' => 'footer_text_right'
		)
	)
);

$themify_theme_config['panel']['settings']['tab']['image_script'] = array(
	'title' => __('Image Script', 'themify'),
	'id' => 'image_script',
	'custom-module' => array(
		array(
			'title' => __('Image Script Settings', 'themify'),
			'function' => 'img_settings'
		)
	)
);

$themify_theme_config['panel']['settings']['tab']['social_links'] = array(
	'title' => __('Social Links', 'themify'),
	'id' => 'social_links',
	'custom-module' => array(
		array(
			'title' => __('Manage Social Links', 'themify'),
			'function' => 'themify_manage_links'
		)
	)
);
